FROM ubuntu:24.04

# Install dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        python3 python3-pip git build-essential lmod less && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install ReFrame (latest release)
RUN git clone -q --depth 1 --branch v4.9.1 https://github.com/reframe-hpc/reframe.git /opt/reframe
RUN cd /opt/reframe && ./bootstrap.sh

# Add ReFrame to PATH
ENV PATH="/opt/reframe/bin:${PATH}"

# Test ReFrame 
RUN reframe --version

# Clone cscs-reframe-tests
#RUN git clone https://github.com/eth-cscs/cscs-reframe-tests /opt/cscs-reframe-tests
RUN git clone -q --depth 1 --branch ReframeContainer https://github.com/gppezzi/cscs-reframe-tests.git /opt/cscs-reframe-tests

ENTRYPOINT ["reframe"]

