FROM docker.io/opensuse/leap:15.5

RUN zypper install -y -t pattern devel_basis \
    && zypper install -y which wget gzip gcc-c++ \
    && zypper clean --all

RUN wget -q http://www.mpich.org/static/downloads/3.1.4/mpich-3.1.4.tar.gz \
    && tar xf mpich-3.1.4.tar.gz \
    && cd mpich-3.1.4 \
    && ./configure --disable-fortran --enable-fast=all,O3 --prefix=/usr \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf mpich-3.1.4 \
    && rm mpich-3.1.4.tar.gz

RUN wget -q http://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.3.2.tar.gz \
    && tar xf osu-micro-benchmarks-5.3.2.tar.gz  \
    && cd osu-micro-benchmarks-5.3.2 \
    && ./configure --prefix=/usr/local CC=$(which mpicc) CFLAGS=-O3 \
    && make \
    && make install \
    && cd .. \
    && rm -rf osu-micro-benchmarks-5.3.2 \
    && rm osu-micro-benchmarks-5.3.2.tar.gz

CMD usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_bw
