FROM docker.io/nvidia/cuda:12.4.1-devel-ubuntu22.04

ARG NODEBURN_COMMIT_ID=be4f759
ARG OPENBLAS_VERSION=0.3.30

RUN apt-get update && \
    apt-get install -y wget git cmake gfortran

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/sbsa/cuda-keyring_1.1-1_all.deb && \
    if [ "$(uname -m)" != "x86_64" ]; then \
        dpkg -i cuda-keyring_1.1-1_all.deb; \
        apt-get update; \
        apt-get -y install -y nvpl; \
    else \
        wget -q https://github.com/OpenMathLib/OpenBLAS/releases/download/v${OPENBLAS_VERSION}/OpenBLAS-${OPENBLAS_VERSION}.tar.gz && \
        tar xzf OpenBLAS-${OPENBLAS_VERSION}.tar.gz && \
        cd OpenBLAS-${OPENBLAS_VERSION} && \
        make -j$(nproc) USE_OPENMP=1 USE_LOCKING=1 DYNAMIC_ARCH=1 NO_AFFINITY=1 && \
        make install PREFIX=/usr/local && \
        ldconfig && \
        cd .. && rm -rf OpenBLAS-${OPENBLAS_VERSION} OpenBLAS-${OPENBLAS_VERSION}.tar.gz; \
    fi && \
    if [ "$(uname -m)" != "x86_64" ]; then \
        mkdir -p /usr/local/lib && touch /usr/local/lib/libopenblasp-r0.3.30.so; \
    fi

RUN git clone https://github.com/eth-cscs/node-burn.git && \
    cd node-burn && \
    git checkout $(NODEBURN_COMMIT_ID) && \
    if [ "$(uname -m)" != "x86_64" ]; then \
        sed -i 's/find_package(BLAS REQUIRED)/find_package(nvpl REQUIRED COMPONENTS blas)/' CMakeLists.txt; \
        sed -i 's/BLAS::BLAS/nvpl::lapack_lp64_omp/' CMakeLists.txt; \
    fi && \
    if [ "$(uname -m)" = "x86_64" ]; then BLA_VENDOR="-DBLA_VENDOR=OpenBLAS"; fi && \
    cmake -DCMAKE_BUILD_TYPE=Release -DTF32=ON -DDOUBLE=OFF $BLA_VENDOR -B build && \
    cmake -DCMAKE_BUILD_TYPE=Release $BLA_VENDOR -B build-f64 && \
    cmake -DNB_GPU=OFF -DCMAKE_BUILD_TYPE=Release -DTF32=ON -DDOUBLE=OFF $BLA_VENDOR -B build-cpu && \
    cmake -DNB_GPU=OFF -DCMAKE_BUILD_TYPE=Release $BLA_VENDOR -B build-f64-cpu && \
    cmake --build build && \
    cmake --build build-f64 && \
    cmake --build build-cpu && \
    cmake --build build-f64-cpu && \
    cp build/burn /usr/local/bin && \
    cp build-f64/burn /usr/local/bin/burn-f64 && \
    cp build-cpu/burn /usr/local/bin/burn-cpu && \
    cp build-f64-cpu/burn /usr/local/bin/burn-f64-cpu && \
    cd .. \
    rm -rf node-burn

FROM docker.io/nvidia/cuda:12.4.1-runtime-ubuntu22.04

COPY --from=0 cuda-keyring_1.1-1_all.deb cuda-keyring_1.1-1_all.deb

RUN  if [ "$(uname -m)" != "x86_64" ]; then \
         dpkg -i cuda-keyring_1.1-1_all.deb; \
         apt-get update; \
         apt-get -y install -y libgomp1 libnvpl-blas0; \
     else \
         apt-get update; \
         apt-get -y install -y libgomp1 libgfortran5; \
     fi

COPY --from=0 /usr/local/lib/libopenblasp-r0.3.30.so /usr/local/lib/
COPY --from=0 /usr/local/bin/burn* /usr/local/bin/
RUN if [ -s /usr/local/lib/libopenblasp-r0.3.30.so ]; then \
        ln -sf libopenblasp-r0.3.30.so /usr/local/lib/libopenblas.so.0 && \
        ln -sf libopenblas.so.0 /usr/local/lib/libopenblas.so; \
    fi && \
    ldconfig
