include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - pull
  - wait
  - reframe

variables:
  MODE: 'f7t-controller'
  WORKSPACE: '$${CI_CACHE_FOLDER}/rfm_workspace'
  JOB_NAME: rfm-$CI_PIPELINE_ID
  # FIRECREST_SYSTEM: 'eiger'
# https://github.com/finkandreas/benchpark/blob/develop/.ci/cscs.yml

setup and pull:
  # extends: .f7t-baremetal-runner
  # extends: .f7t-runner
  stage: pull
  tags: ['f7t-runner']
  # tags: ['eiger-login-baremetal']
  # tags: ['baremetal-runner-eiger-mc-f7t']
  variables:
    GIT_STRATEGY: "fetch"
    # STACK_MOUNT:      "/user-environment"
    # STACK_NAME:       "prgenv-gnu/23.11"
    # STACK_SYSTEM:     "eiger"
    # STACK_UARCH:      "zen2"
    SLURM_PARTITION: "debug"
    SLURM_CONSTRAINT: "mc"
    F7T_TOKEN_URL: "https://auth.cscs.ch/auth/realms/firecrest-clients/protocol/openid-connect/token"
    F7T_URL: "https://firecrest.cscs.ch"
    MODE: "baremetal"
    SLURM_ACCOUNT: "csstaff"
    FIRECREST_SYSTEM: "eiger"
  script:
    - id
    - pwd
    - uname -a
    # - ./ci/scripts/alps_uenv.sh setup_oras
    - export PATH=$PWD:$PATH
    # - oras version
    - ./ci/scripts/alps_uenv.sh setup_jq
    - ./ci/scripts/alps_uenv.sh setup_uenv_and_oras &> setup_uenv_and_oras.log
    - source ./uenv-4.0.1/bin/activate-uenv
    - uenv --version
    - export PATH=$UENV_PREFIX/libexec:$PATH
    - uenv-oras version
    - ./ci/scripts/alps_uenv.sh jfrog_login
    - imgs=$(./ci/scripts/alps_uenv.sh uenv_image_find)
    - echo "imgs=$imgs"
    - img0=$(echo $imgs | cut -d' ' -f1)
    - echo "img0=$img0"
    # - oras_pull_meta_dir
    # - echo "PATH=$PATH" | tr : "\n"
    # - which oras
    # - uenv --version
    # - export RFM_AUTODETECT_XTHOSTNAME=1
