include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - run

run rfm_test:
  stage: run
  tags: [daint-login-baremetal]
  variables:
    GIT_STRATEGY: fetch
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_PROJECT_NAME
  script:
    - rm -rf reframe
    - git clone https://github.com/reframe-hpc/reframe.git
    - cd reframe
    - ./bootstrap.sh
    - ./bin/reframe -t production -C ../config/cscs.py -c ../checks/ --report-junit=../report.xml -r
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
