include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - run
  - notify
  # - status

reframe:
  stage: run
  extends: .f7t-baremetal-runner
  timeout: 8 hours
  variables:
    SLURM_TIMELIMIT: '02:00:00'
  before_script:
    - echo "FIRECREST_SYSTEM=$FIRECREST_SYSTEM / F7T_URL=$F7T_URL / CLUSTER_NAME=$CLUSTER_NAME"
    - uname -a
    - pwd
  script:
    - hostname
    - rfm_path=$(./ci/scripts/alps.sh install_reframe)
    - echo "rfm_path=$rfm_path"
    - export PATH=$rfm_path:$PATH
    - reframe -V
    - ./ci/scripts/alps.sh launch_reframe_1arg "--mode cpe_production"
  artifacts:
    when: always
    # on_failure
    paths:
      - reframe.out
      - report.xml
      - latest.json
    reports:
      junit: report.xml

# status_page:
#   stage: status
#   needs: ['reframe']
#   extends: .container-runner-lightweight-zen2
#   image: python:3.9
#   script:
#     - pwd
#     - ls -a
#     - pip install requests
#     - ./ci/scripts/alps.sh oneuptime "$FIRECREST_SYSTEM" "cpe"
#   when: always

notify_slack:
  stage: notify
  needs: ['reframe']
  extends: .container-runner-lightweight-zen2
  image: python:3.9
  script:
    - pwd
    - ls -a
    - pip install requests
    - python ./ci/scripts/slack_notify.py latest.json
  when: always

