include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - pull
  - wait
  - reframe

variables:
  MODE: 'f7t-controller'
  WORKSPACE: '$${CI_CACHE_FOLDER}/rfm_workspace'
  JOB_NAME: rfm-$CI_PIPELINE_ID
  # FIRECREST_SYSTEM: 'eiger'
# https://github.com/finkandreas/benchpark/blob/develop/.ci/cscs.yml

run rfm_test:
  # extends: .f7t-baremetal-runner
  extends: .f7t-runner
  stage: reframe
  # tags: ['eiger-login-baremetal']
  # tags: ['baremetal-runner-eiger-mc-f7t']
  tags: ['f7t-runner']
  variables:
    GIT_STRATEGY: fetch
  script:
    - pwd
    - oras_path=$(./ci/scripts/alps_uenv.sh setup_oras)
    - export PATH=$oras_path:$PATH
    - echo "PATH=$PATH"
    - ls -l $oras_path/
    # - echo "PATH=$PATH" | tr : "\n"
    # - which oras
    # - uenv --version
    # - export RFM_AUTODETECT_XTHOSTNAME=1
  variables:
    SLURM_CONSTRAINT: mc
    SLURM_PARTITION: debug
