include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - run
  - notify
  # - status

reframe:
  stage: run
  extends: .f7t-baremetal-runner
  timeout: 8 hours
  variables:
    SLURM_TIMELIMIT: '02:00:00'
  before_script:
    - echo "FIRECREST_SYSTEM=$FIRECREST_SYSTEM / F7T_URL=$F7T_URL / CLUSTER_NAME=$CLUSTER_NAME"
    - uname -a
    - pwd
    # Send data to elastic on main branch only
    - '[ "$CI_COMMIT_REF_NAME" != "main" ] && unset RFM_HTTPJSON_URL'
    - git remote add oripr https://github.com/eth-cscs/cscs-reframe-tests || true
    - 'echo "it is safe to ignore error: remote already exists"'
    - git remote -v
    - hostname
  script:
    - rfm_path=$(./ci/scripts/alps.sh install_reframe)
    - export PATH=$rfm_path:$PATH
    - reframe -V
    # If in a PR, run only the tests modified in the PR; if not, all tests
    - echo "CI_PIPELINE_SOURCE=$CI_PIPELINE_SOURCE CRON_RUN=$CRON_RUN"
    - |
      if [ "$CRON_RUN" = "true" ]; then
        ./ci/scripts/alps.sh launch_reframe_1arg "--mode daily_production";
      else
        git fetch oripr main;
        git diff --name-only oripr/main;
        tests_pr=$(git diff --name-only oripr/main |grep checks |grep py$ |awk '{printf "-c %s ",$0}');
        if [ -z "$tests_pr" ]; then
          echo "no new/modified test(s) found, exiting";
          exit 0
        else
          echo "tests_pr=$tests_pr";
          ./ci/scripts/alps.sh launch_reframe_1arg "$tests_pr";
        fi
      fi
  artifacts:
    when: always
    paths:
      - reframe.out
      - report.xml
      - latest.json
    reports:
      junit: report.xml

# status_page:
#   stage: status
#   needs: ['reframe']
#   extends: .container-runner-lightweight-zen2
#   image: python:3.9
#   script:
#     - pwd
#     - ls -a
#     - pip install requests
#     - ./ci/scripts/alps.sh oneuptime "$FIRECREST_SYSTEM" "cpe"
#   when: always

notify_slack:
  stage: notify
  needs: ['reframe']
  extends: .container-runner-lightweight-zen2
  image: python:3.9
  script:
    - pwd
    - ls -a
    - pip install requests
    - python ./ci/scripts/slack_notify.py latest.json cpe
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never
