include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - pull
  - wait
  - reframe

variables:
  MODE: 'f7t-controller'
  FIRECREST_SYSTEM: 'eiger'
  WORKSPACE: '$${CI_CACHE_FOLDER}/rfm_workspace'
  JOB_NAME: rfm-$CI_PIPELINE_ID
# https://github.com/finkandreas/benchpark/blob/develop/.ci/cscs.yml

run rfm_test:
  extends: .f7t-baremetal-runner
  stage: reframe
  # tags: ['eiger-login-baremetal']
  # tags: ['baremetal-runner-eiger-mc-f7t']
  tags: ['f7t-runner']
  variables:
    GIT_STRATEGY: fetch
  script:
    - WORKSPACE="$(eval echo $WORKSPACE)"
    - echo "Using WORKSPACE=$WORKSPACE"
    - uname -a
    - export RFM_AUTODETECT_XTHOSTNAME=1
    - pwd
    - ls -la
    - firecrest --version
  variables:
    SLURM_CONSTRAINT: mc
    SLURM_PARTITION: debug
#del       - ./bin/reframe -C ../config/cscs-uenv.py ../checks/uenv --report-junit=../report.xml -r
#del   artifacts:
#del     when: always
#del     paths:
#del       - report.xml
#del     reports:
#del       junit: report.xml
