include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - run

run rfm_test:
  stage: run
  tags: ['clariden-login-baremetal']
  script:
    - rm -fr venv_reframe_cpe
    - python3 -m venv venv_reframe_cpe
    - source venv_reframe_cpe/bin/activate
    - pip install reframe-hpc
    - |
      # Use || true so that the following command does return exit code
      changedtests=( $(git diff origin/alps...HEAD --name-only --oneline --no-merges | grep -e '^checks/.*\.py' || true) )

      if [ ${#changedtests[@]} -ne 0 ]; then
          changedtests_path=""
          for check in ${changedtests[@]}; do
              changedtests_path="${changedtests_path} -c ${check}"
          done

          reframe -C config/cscs.py ${changedtests_path} --report-junit=reportcpe.xml -r
      fi

    - deactivate
  artifacts:
    when: on_failure
    paths:
      - reportcpe.xml
    reports:
      junit: reportcpe.xml
