include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - run

run rfm_test:
  extends: .container-runner-hohgant
  stage: run
  tags: ['hohgant-login-baremetal']
  variables:
    GIT_STRATEGY: fetch
  script:
    - rm -rf reframe
    - git clone -b feat/prepare_cmds_env https://github.com/teojgo/reframe.git
    - cd reframe
    - ./bootstrap.sh
    - export RFM_AUTODETECT_XTHOSTNAME=1
    - ./bin/reframe -C ../config/cscs-uenv.py -c ../checks/uenv --report-junit=../report.xml -r
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml
