include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - run

run rfm_test:
  stage: run
  tags: ['santis-login-baremetal']
  variables:
    UENV: '/bret/scratch/cscs/bcumming/images/prgenv-gnu-24.2-v2.squashfs'
    REPORT: 'report_daily.xml'
  script: ./ci/systems-uenv/santis_login_baremetal_daily_checks.sh $REPORT
  artifacts:
    when: on_failure 
    paths:
      - $REPORT
    reports:
      junit: $REPORT
