model: unet3d

framework: pytorch

workflow:
  generate_data: False
  train: True
  checkpoint: True

dataset:
  data_folder: data/unet3d/
  format: npz
  num_files_train: 168
  num_samples_per_file: 1
  record_length: 146600628
  record_length_stdev: 68341808
  record_length_resize: 2097152

reader:
  data_loader: pytorch
  batch_size: 8
  read_threads: 6
  file_shuffle: seed
  sample_shuffle: seed

train:
  epochs: 2
  computation_time: 1.0e-6  # raw IO benchmark

checkpoint:
  checkpoint_folder: checkpoints/unet3d
  checkpoint_after_epoch: 2
  epochs_between_checkpoints: 2
  model_size: 499153191
