ARG BASE=docker.io/nvidia/cuda:12.8.1-devel-ubuntu22.04

FROM $BASE

ARG MPICH_VER=4.3.0
ARG GDRCOPY_VER=2.5

RUN apt-get update && \
    apt-get install -y autoconf libtool git wget libhwloc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget -q http://www.mpich.org/static/downloads/${MPICH_VER}/mpich-${MPICH_VER}.tar.gz \
    && tar xf mpich-${MPICH_VER}.tar.gz \
    && cd mpich-${MPICH_VER} \
    && ./configure --disable-fortran --with-device=ch3:sock -prefix=/usr \
    && make -j 3 \
    && make install \
    && cd .. \
    && rm -rf mpich-${MPICH_VER} \
    && rm mpich-${MPICH_VER}.tar.gz

RUN git clone -b v${GDRCOPY_VER} https://github.com/NVIDIA/gdrcopy.git && \
    cd gdrcopy && \
    export CUDA_PATH=${CUDA_HOME:-$(echo $(which nvcc) | grep -o '.*cuda')} && \
    make CC=gcc CUDA=$CUDA_PATH lib && \
    make lib_install && \
    cd ../ && rm -rf gdrcopy

RUN git clone https://github.com/NVIDIA/nccl-tests.git && \
    cd nccl-tests && \
    CXX=mpicxx make MPI=1 -j 4 && \
    cp $(find build/ -type f -executable) /usr/local/bin && \
    cd ../ && \
    rm -rf nccl-tests

FROM docker.io/nvidia/cuda:12.8.1-runtime-ubuntu22.04

RUN apt update && \
    apt install -y libhwloc15 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=0 /usr/local/bin/* /usr/local/bin
COPY --from=0 /usr/local/lib/libgdr* /usr/local/lib
COPY --from=0 /usr/lib/libmpi* /usr/lib
