name: ReFrame CI

on: [push, pull_request]

jobs:
  codechecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Lint Code Base
      uses: github/super-linter@v7
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_PYTHON_FLAKE8: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
