name: ReFrame CI

on: [push, pull_request]

jobs:
  codechecker:
    runs-on: ubuntu-latest

    permissions:
      # contents permission to clone the repository
      contents: read
      packages: read
      # issues and pull-requests permissions to write results as pull
      # request comments. Omit them if you don't need summary comments
      # issues: write
      pull-requests: write
      # To report GitHub Actions status checks. Omit if you don't need
      # to update commit status
      statuses: write

    steps:
      - name: Checkout code 
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_FLAKE8: true
