FROM debian:11.6

RUN apt-get update && apt-get install -y \
        build-essential             \
        wget                        \
        ca-certificates             \
        --no-install-recommends     \
    && rm -rf /var/lib/apt/lists/*

RUN wget -q http://www.mpich.org/static/downloads/3.1.4/mpich-3.1.4.tar.gz \
    && tar xf mpich-3.1.4.tar.gz \
    && cd mpich-3.1.4 \
    && ./configure --disable-fortran --enable-fast=all,O3 --prefix=/usr \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf mpich-3.1.4 \
    && rm mpich-3.1.4.tar.gz

RUN wget -q http://mvapich.cse.ohio-state.edu/download/mvapich/osu-micro-benchmarks-5.3.2.tar.gz \
    && tar xf osu-micro-benchmarks-5.3.2.tar.gz  \
    && cd osu-micro-benchmarks-5.3.2 \
    && ./configure --prefix=/usr/local CC=$(which mpicc) CFLAGS=-O3 \
    && make \
    && make install \
    && cd .. \
    && rm -rf osu-micro-benchmarks-5.3.2 \
    && rm osu-micro-benchmarks-5.3.2.tar.gz

CMD /usr/local/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_bw
